### ISSUE TITLE
Update BTSPAS-X to work with new data structure 

### ISSUE THREAD

**Issue by ErinCain** [SRJPE/SRJPEmodel#13]
SRJPEdata now exports 2 tables for BTSPAS-X. 

One is `weekly_juvenile_abundance_catch_data.` This table looks a lot like the current `weekly_juvenile_abundance_model_data` but we have removed the efficiency related columns. 

There is another table `weekly_juvenile_abundance_efficiency_data` that contains all the distinct weekly efficiency data.

**Comment by liz-fw** [comment]
addressed in `wip`
